language: cpp

matrix:
 include:
  - if: tag IS blank
    os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=59
  - if: tag IS blank
    os: osx
    compiler: clang
    env:
     - QT_BASE=59
  fast_finish: true

cache: packages

before_install:
  - if [[ "$QT_BASE" = "59" && "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  # Needed for a C++14 compiler
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install -qq g++-5;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90;
    fi
  # Install Qt
  - if [ "$QT_BASE" = "59" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt59base ;
        sudo apt-get install -qq qt59charts-no-lgpl ;
        sudo apt-get install -qq qt59imageformats ;
        sudo apt-get install -qq qt59multimedia ;
        sudo apt-get install -qq qt59svg ;
        sudo apt-get install -qq qt59webengine ;
        sudo apt-get install -qq qt59tools ;
        source /opt/qt59/bin/qt59-env.sh;
      else
        brew install qt5;
        brew link --force qt5;
        export HOMEBREW_QT5_VERSION=$(brew list --versions qt5 | rev | cut -d' ' -f1 | rev);
        ln -s /usr/local/Cellar/qt5/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
      fi
    fi

script:
  # Check versions
  - g++ -v;
  - qmake -v;
  # Create build directory
  - mkdir ./build && cd ./build
  # Build Praaline dependencies
  - qmake ../praaline-dependencies.pro CONFIG+=release && make && cd ..
  - ls -R
  # Package
  - mkdir deploy
  - cp build/qscintilla/Qt4Qt5/libqscintilla*.* deploy
  - cp qtilities/bin/*.* deploy
  - cp qt-solutions/qtpropertybrowser/lib/*.* deploy
  - tar -czv --exclude='.*' -f praaline_dependencies_${TRAVIS_OS_NAME}.tar.gz deploy

before_deploy:
  # Set up git user name and tag for this commit
  - git config --local user.name "praaline"
  - git config --local user.email "info@praaline.org"
  - git tag -f "$(date +'%Y-%m-%d')"

deploy:
  provider: releases
  api-key:
    secure: LB2wnB1x31KbSmgbOK6Buv1ioap+W21tWcHhzLATMZGC6Y9RfHUS8Fd3tsjL+B2vzHCpmrgbnbVkkazmPrGNF30404a7t2eJowj3zrOe3dLhA9AejwTBxc3X+CUnr7ARF2QLpwKQ+AB9FJDeyFHFbqOcghjat5TtiDqN1ZAOV+Dn69TUw8tubzWuE9/AWCFGpvjpDFPEduaN4YBcc/jXplAKwIUM15N4CsicYN0aHWRx5AKb6tfJF8Fs6ub5CyNQTzpqvwF0WEVkNOs/dmjwxRR5HlzAFc2StTL1GnrQ1dukTPTfP6waMZHQLtrVwWHsAymYIgR6aWZaAFjUcfgIT+qE/92/snl07zLzoO1QM1jjAcqeskXoXsDQ5hLReu0vEijWkjLp19jqsWyrPmxQ28owH2IA7o3JCf2a4Wn5dU6Uc+EAhTmbUhQHkLb6iBfHFapm0ubf6yCak1KUJxPASrt0gEYWkUZmoWw+PF53+jYS5CxpwdW3s0BXqCJILJs5/2zHNKDYpwNLAtUDx6pywOphhTz843XhvWBNdrdJxJk9V/UoqBqBdgN3T8aguh25FbW75gpI0fLnAxnFqELEc8Ni54pZ1+epRrrTTDFTo+8HQfSBcN/9M2NlPRdTLrSYW1bQRH2KP7+9Czx3b+LvGGmeWh1R5kOabXTjHAAOobI=
  name: $(date +'%Y-%m-%d')
  file: praaline_dependencies_${TRAVIS_OS_NAME}.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    repo: praaline/praaline-dependencies
    all_branches: true

notifications:
  email: false

