/********************************************************************************
** Form generated from reading UI file 'NamingPolicyInputDialog.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NAMINGPOLICYINPUTDIALOG_H
#define UI_NAMINGPOLICYINPUTDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QVBoxLayout>

QT_BEGIN_NAMESPACE

class Ui_NamingPolicyInputDialog
{
public:
    QVBoxLayout *verticalLayout_2;
    QLabel *lblHeading;
    QFormLayout *formLayout;
    QLabel *label_2;
    QLabel *lblContext;
    QLabel *label_6;
    QLabel *lblOriginalName;
    QLabel *label_5;
    QLabel *lblProblemDescription;
    QFrame *line;
    QGroupBox *groupBox;
    QVBoxLayout *verticalLayout;
    QRadioButton *radioDifferentName;
    QHBoxLayout *horizontalLayout;
    QSpacerItem *horizontalSpacer_2;
    QLabel *label_3;
    QLineEdit *txtDifferentName;
    QToolButton *btnDifferentNameValidityIndicator;
    QRadioButton *radioAutoRename;
    QHBoxLayout *horizontalLayout_2;
    QSpacerItem *horizontalSpacer_3;
    QLabel *label_4;
    QLineEdit *txtAutoGeneratedName;
    QToolButton *btnGenerateNewName;
    QRadioButton *radioReplaceConflicting;
    QRadioButton *radioReject;
    QSpacerItem *verticalSpacer;
    QHBoxLayout *horizontalLayout_3;
    QCheckBox *chkAllInThisCycle;
    QSpacerItem *horizontalSpacer;
    QDialogButtonBox *buttonBox;

    void setupUi(QDialog *NamingPolicyInputDialog)
    {
        if (NamingPolicyInputDialog->objectName().isEmpty())
            NamingPolicyInputDialog->setObjectName(QStringLiteral("NamingPolicyInputDialog"));
        NamingPolicyInputDialog->resize(486, 323);
        verticalLayout_2 = new QVBoxLayout(NamingPolicyInputDialog);
        verticalLayout_2->setObjectName(QStringLiteral("verticalLayout_2"));
        lblHeading = new QLabel(NamingPolicyInputDialog);
        lblHeading->setObjectName(QStringLiteral("lblHeading"));

        verticalLayout_2->addWidget(lblHeading);

        formLayout = new QFormLayout();
        formLayout->setObjectName(QStringLiteral("formLayout"));
        label_2 = new QLabel(NamingPolicyInputDialog);
        label_2->setObjectName(QStringLiteral("label_2"));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_2->setFont(font);

        formLayout->setWidget(0, QFormLayout::LabelRole, label_2);

        lblContext = new QLabel(NamingPolicyInputDialog);
        lblContext->setObjectName(QStringLiteral("lblContext"));

        formLayout->setWidget(0, QFormLayout::FieldRole, lblContext);

        label_6 = new QLabel(NamingPolicyInputDialog);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setFont(font);

        formLayout->setWidget(1, QFormLayout::LabelRole, label_6);

        lblOriginalName = new QLabel(NamingPolicyInputDialog);
        lblOriginalName->setObjectName(QStringLiteral("lblOriginalName"));

        formLayout->setWidget(1, QFormLayout::FieldRole, lblOriginalName);

        label_5 = new QLabel(NamingPolicyInputDialog);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setFont(font);

        formLayout->setWidget(2, QFormLayout::LabelRole, label_5);

        lblProblemDescription = new QLabel(NamingPolicyInputDialog);
        lblProblemDescription->setObjectName(QStringLiteral("lblProblemDescription"));

        formLayout->setWidget(2, QFormLayout::FieldRole, lblProblemDescription);


        verticalLayout_2->addLayout(formLayout);

        line = new QFrame(NamingPolicyInputDialog);
        line->setObjectName(QStringLiteral("line"));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);

        verticalLayout_2->addWidget(line);

        groupBox = new QGroupBox(NamingPolicyInputDialog);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        verticalLayout = new QVBoxLayout(groupBox);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        radioDifferentName = new QRadioButton(groupBox);
        radioDifferentName->setObjectName(QStringLiteral("radioDifferentName"));
        radioDifferentName->setChecked(true);

        verticalLayout->addWidget(radioDifferentName);

        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalSpacer_2 = new QSpacerItem(17, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_2);

        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));

        horizontalLayout->addWidget(label_3);

        txtDifferentName = new QLineEdit(groupBox);
        txtDifferentName->setObjectName(QStringLiteral("txtDifferentName"));

        horizontalLayout->addWidget(txtDifferentName);

        btnDifferentNameValidityIndicator = new QToolButton(groupBox);
        btnDifferentNameValidityIndicator->setObjectName(QStringLiteral("btnDifferentNameValidityIndicator"));
        btnDifferentNameValidityIndicator->setEnabled(true);
        btnDifferentNameValidityIndicator->setAutoRaise(true);

        horizontalLayout->addWidget(btnDifferentNameValidityIndicator);


        verticalLayout->addLayout(horizontalLayout);

        radioAutoRename = new QRadioButton(groupBox);
        radioAutoRename->setObjectName(QStringLiteral("radioAutoRename"));
        radioAutoRename->setChecked(false);

        verticalLayout->addWidget(radioAutoRename);

        horizontalLayout_2 = new QHBoxLayout();
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        horizontalSpacer_3 = new QSpacerItem(17, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);

        horizontalLayout_2->addItem(horizontalSpacer_3);

        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setEnabled(false);

        horizontalLayout_2->addWidget(label_4);

        txtAutoGeneratedName = new QLineEdit(groupBox);
        txtAutoGeneratedName->setObjectName(QStringLiteral("txtAutoGeneratedName"));
        txtAutoGeneratedName->setEnabled(false);
        txtAutoGeneratedName->setReadOnly(true);

        horizontalLayout_2->addWidget(txtAutoGeneratedName);

        btnGenerateNewName = new QToolButton(groupBox);
        btnGenerateNewName->setObjectName(QStringLiteral("btnGenerateNewName"));
        btnGenerateNewName->setEnabled(false);
        btnGenerateNewName->setAutoRaise(true);

        horizontalLayout_2->addWidget(btnGenerateNewName);


        verticalLayout->addLayout(horizontalLayout_2);

        radioReplaceConflicting = new QRadioButton(groupBox);
        radioReplaceConflicting->setObjectName(QStringLiteral("radioReplaceConflicting"));

        verticalLayout->addWidget(radioReplaceConflicting);

        radioReject = new QRadioButton(groupBox);
        radioReject->setObjectName(QStringLiteral("radioReject"));

        verticalLayout->addWidget(radioReject);

        verticalSpacer = new QSpacerItem(20, 13, QSizePolicy::Minimum, QSizePolicy::Expanding);

        verticalLayout->addItem(verticalSpacer);


        verticalLayout_2->addWidget(groupBox);

        horizontalLayout_3 = new QHBoxLayout();
        horizontalLayout_3->setObjectName(QStringLiteral("horizontalLayout_3"));
        chkAllInThisCycle = new QCheckBox(NamingPolicyInputDialog);
        chkAllInThisCycle->setObjectName(QStringLiteral("chkAllInThisCycle"));

        horizontalLayout_3->addWidget(chkAllInThisCycle);

        horizontalSpacer = new QSpacerItem(168, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_3->addItem(horizontalSpacer);

        buttonBox = new QDialogButtonBox(NamingPolicyInputDialog);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Ok);

        horizontalLayout_3->addWidget(buttonBox);


        verticalLayout_2->addLayout(horizontalLayout_3);

#ifndef QT_NO_SHORTCUT
        label_3->setBuddy(txtDifferentName);
        label_4->setBuddy(txtAutoGeneratedName);
#endif // QT_NO_SHORTCUT
        QWidget::setTabOrder(radioDifferentName, txtDifferentName);
        QWidget::setTabOrder(txtDifferentName, radioAutoRename);
        QWidget::setTabOrder(radioAutoRename, txtAutoGeneratedName);
        QWidget::setTabOrder(txtAutoGeneratedName, btnGenerateNewName);
        QWidget::setTabOrder(btnGenerateNewName, radioReplaceConflicting);
        QWidget::setTabOrder(radioReplaceConflicting, radioReject);
        QWidget::setTabOrder(radioReject, buttonBox);
        QWidget::setTabOrder(buttonBox, btnDifferentNameValidityIndicator);

        retranslateUi(NamingPolicyInputDialog);
        QObject::connect(buttonBox, SIGNAL(accepted()), NamingPolicyInputDialog, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), NamingPolicyInputDialog, SLOT(reject()));
        QObject::connect(radioAutoRename, SIGNAL(toggled(bool)), txtAutoGeneratedName, SLOT(setEnabled(bool)));
        QObject::connect(radioDifferentName, SIGNAL(toggled(bool)), txtDifferentName, SLOT(setEnabled(bool)));
        QObject::connect(radioAutoRename, SIGNAL(toggled(bool)), btnGenerateNewName, SLOT(setEnabled(bool)));
        QObject::connect(radioDifferentName, SIGNAL(toggled(bool)), label_3, SLOT(setEnabled(bool)));
        QObject::connect(radioAutoRename, SIGNAL(toggled(bool)), label_4, SLOT(setEnabled(bool)));
        QObject::connect(radioDifferentName, SIGNAL(toggled(bool)), btnDifferentNameValidityIndicator, SLOT(setEnabled(bool)));

        QMetaObject::connectSlotsByName(NamingPolicyInputDialog);
    } // setupUi

    void retranslateUi(QDialog *NamingPolicyInputDialog)
    {
        NamingPolicyInputDialog->setWindowTitle(QApplication::translate("NamingPolicyInputDialog", "Naming Problem Detected", Q_NULLPTR));
        lblHeading->setText(QApplication::translate("NamingPolicyInputDialog", "A naming problem has been detected with the name of the following object:", Q_NULLPTR));
        label_2->setText(QApplication::translate("NamingPolicyInputDialog", "Context:", Q_NULLPTR));
        lblContext->setText(QApplication::translate("NamingPolicyInputDialog", "Context not specified", Q_NULLPTR));
        label_6->setText(QApplication::translate("NamingPolicyInputDialog", "Object Name:", Q_NULLPTR));
        lblOriginalName->setText(QApplication::translate("NamingPolicyInputDialog", "Object Name", Q_NULLPTR));
        label_5->setText(QString());
        lblProblemDescription->setText(QApplication::translate("NamingPolicyInputDialog", "Problem description", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("NamingPolicyInputDialog", "If you want to continue, please select how you want to resolve this:", Q_NULLPTR));
        radioDifferentName->setText(QApplication::translate("NamingPolicyInputDialog", "Use a different name.", Q_NULLPTR));
        label_3->setText(QApplication::translate("NamingPolicyInputDialog", "Please specify a new name:", Q_NULLPTR));
        btnDifferentNameValidityIndicator->setText(QApplication::translate("NamingPolicyInputDialog", "...", Q_NULLPTR));
        radioAutoRename->setText(QApplication::translate("NamingPolicyInputDialog", "Auto-rename the object for me.", Q_NULLPTR));
        label_4->setText(QApplication::translate("NamingPolicyInputDialog", "The following name will be used:", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        btnGenerateNewName->setToolTip(QApplication::translate("NamingPolicyInputDialog", "Generate again", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        btnGenerateNewName->setText(QApplication::translate("NamingPolicyInputDialog", "...", Q_NULLPTR));
        radioReplaceConflicting->setText(QApplication::translate("NamingPolicyInputDialog", "Replace the existing (conflicting) object with the new object.", Q_NULLPTR));
        radioReject->setText(QApplication::translate("NamingPolicyInputDialog", "Reject (Cancel this operation)", Q_NULLPTR));
        chkAllInThisCycle->setText(QApplication::translate("NamingPolicyInputDialog", "All in this cycle", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class NamingPolicyInputDialog: public Ui_NamingPolicyInputDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NAMINGPOLICYINPUTDIALOG_H
